#!/usr/bin/env python3
"""Convert binary files into a single C source of byte arrays.

Emits arrays guarded by #ifdef NETBIN so the generated file compiles to an
empty object in the CD build, which globs every src/*.c unconditionally.

Usage:
    python3 tools/gen_blob.py OUT.c NAME=PATH [NAME=PATH ...]
"""
import sys


def emit_array(name, data):
    out = [f"const unsigned char netbin_{name}_bytes[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    out.append("};")
    out.append(f"const unsigned int netbin_{name}_len = {len(data)}u;")
    return "\n".join(out)


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2
    out_path, specs = argv[1], argv[2:]

    parts = [
        "/* GENERATED by tools/gen_blob.py -- do not edit by hand. */",
        '#include "netbin_blobs.h"',
        "",
        "#ifdef NETBIN",
        "",
    ]
    accessors = []
    for spec in specs:
        if "=" not in spec:
            sys.stderr.write(f"gen_blob: bad spec {spec!r}, want NAME=PATH\n")
            return 2
        name, path = spec.split("=", 1)
        with open(path, "rb") as fh:
            data = fh.read()
        if not data:
            sys.stderr.write(f"gen_blob: {path} is empty\n")
            return 1
        parts.append(emit_array(name, data))
        parts.append("")
        accessors.append(
            f"const unsigned char *netbin_{name}_data(void)"
            f" {{ return netbin_{name}_bytes; }}\n"
            f"unsigned int netbin_{name}_size(void)"
            f" {{ return netbin_{name}_len; }}"
        )
        sys.stderr.write(f"gen_blob: {name} <- {path} ({len(data)} bytes)\n")

    parts.extend(accessors)
    parts.append("")
    parts.append("#else  /* !NETBIN -- CD build links no payload */")
    parts.append("")
    for spec in specs:
        name = spec.split("=", 1)[0]
        parts.append(
            f"const unsigned char *netbin_{name}_data(void) {{ return 0; }}\n"
            f"unsigned int netbin_{name}_size(void) {{ return 0u; }}"
        )
    parts.append("")
    parts.append("#endif")
    parts.append("")

    with open(out_path, "w", newline="\n") as fh:
        fh.write("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
