#!/usr/bin/env python3
"""Convert binary files into a single C source of byte arrays.

Emits arrays guarded by #ifdef NETBIN so the generated file compiles to an
empty object in the CD build, which globs every src/*.c unconditionally.

A payload named with --pack is stored DEFLATE-compressed (raw, RFC 1951) and
inflated on first access with puff() (src/puff.c) into a .bss buffer, so it
costs its compressed size on the wire but its full size only in zero-init RAM.
netbin_<name>_data() returns the inflated buffer; netbin_<name>_size() returns
the uncompressed length.

Usage:
    python3 tools/gen_blob.py OUT.c [--pack NAME] NAME=PATH [NAME=PATH ...]
"""
import sys
import zlib


def emit_array(name, data, suffix="bytes"):
    out = [f"const unsigned char netbin_{name}_{suffix}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    out.append("};")
    return "\n".join(out)


def deflate_raw(data):
    """Raw DEFLATE (no zlib/gzip wrapper) at max compression -- what puff wants."""
    c = zlib.compressobj(9, zlib.DEFLATED, -15)
    return c.compress(data) + c.flush()


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2

    args = argv[1:]
    out_path = None
    pack = set()
    specs = []
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--pack":
            i += 1
            if i >= len(args):
                sys.stderr.write("gen_blob: --pack needs a NAME\n")
                return 2
            pack.add(args[i])
        elif out_path is None and "=" not in a:
            out_path = a
        else:
            specs.append(a)
        i += 1

    if out_path is None or not specs:
        sys.stderr.write(__doc__)
        return 2

    parts = [
        "/* GENERATED by tools/gen_blob.py -- do not edit by hand. */",
        '#include "netbin_blobs.h"',
        "",
        "#ifdef NETBIN",
        "",
    ]
    if pack:
        parts.append('#include "puff.h"')
        parts.append("")

    for spec in specs:
        if "=" not in spec:
            sys.stderr.write(f"gen_blob: bad spec {spec!r}, want NAME=PATH\n")
            return 2
        name, path = spec.split("=", 1)
        with open(path, "rb") as fh:
            data = fh.read()
        if not data:
            sys.stderr.write(f"gen_blob: {path} is empty\n")
            return 1
        raw_len = len(data)

        if name in pack:
            packed = deflate_raw(data)
            # Guard against a compressor that doesn't shrink the payload.
            if len(packed) >= raw_len:
                sys.stderr.write(
                    f"gen_blob: {name} did not compress "
                    f"({len(packed)} >= {raw_len}); storing uncompressed\n")
                parts.append(emit_array(name, data))
                parts.append(f"const unsigned int netbin_{name}_len = {raw_len}u;")
                parts.append("")
                parts.append(
                    f"const unsigned char *netbin_{name}_data(void)"
                    f" {{ return netbin_{name}_bytes; }}\n"
                    f"unsigned int netbin_{name}_size(void)"
                    f" {{ return netbin_{name}_len; }}")
                parts.append("")
                sys.stderr.write(
                    f"gen_blob: {name} <- {path} ({raw_len} bytes, stored)\n")
                continue

            parts.append(
                f"/* {name}: raw DEFLATE of {path} ({raw_len} -> {len(packed)}"
                f" bytes); inflated into .bss on first access. */")
            parts.append(emit_array(name, packed, "packed"))
            parts.append(f"static unsigned char netbin_{name}_buf[{raw_len}];")
            parts.append(f"static int netbin_{name}_ready = 0;")
            parts.append("")
            parts.append(
                f"const unsigned char *netbin_{name}_data(void) {{\n"
                f"    if (!netbin_{name}_ready) {{\n"
                f"        unsigned long dl = {raw_len}UL, sl = {len(packed)}UL;\n"
                f"        if (puff(netbin_{name}_buf, &dl, netbin_{name}_packed, &sl) != 0"
                f" || dl != {raw_len}UL)\n"
                f"            return 0;   /* inflate failed -- corrupt blob */\n"
                f"        netbin_{name}_ready = 1;\n"
                f"    }}\n"
                f"    return netbin_{name}_buf;\n"
                f"}}\n"
                f"unsigned int netbin_{name}_size(void) {{ return {raw_len}u; }}")
            parts.append("")
            sys.stderr.write(
                f"gen_blob: {name} <- {path} "
                f"({raw_len} -> {len(packed)} bytes, deflate)\n")
        else:
            parts.append(emit_array(name, data))
            parts.append(f"const unsigned int netbin_{name}_len = {raw_len}u;")
            parts.append("")
            parts.append(
                f"const unsigned char *netbin_{name}_data(void)"
                f" {{ return netbin_{name}_bytes; }}\n"
                f"unsigned int netbin_{name}_size(void)"
                f" {{ return netbin_{name}_len; }}")
            parts.append("")
            sys.stderr.write(f"gen_blob: {name} <- {path} ({raw_len} bytes)\n")

    parts.append("#else  /* !NETBIN -- CD build links no payload */")
    parts.append("")
    for spec in specs:
        name = spec.split("=", 1)[0]
        parts.append(
            f"const unsigned char *netbin_{name}_data(void) {{ return 0; }}\n"
            f"unsigned int netbin_{name}_size(void) {{ return 0u; }}")
    parts.append("")
    parts.append("#endif")
    parts.append("")

    with open(out_path, "w", newline="\n") as fh:
        fh.write("\n".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
